Repository analogdevicesinc/precision-converters-firmware, pull requests merged in 2025-01, with the labels that each got.

#116 doc: ad2s1210: Update readme file and doc
  doc/sphinx/source/projects/ad2s1210_iio/ad2s1210_iio.rst
  projects/ad2s1210_iio/README.txt
Labels: documentation, minor_updates

#111 Ad3530r doc
  doc/sphinx/source/projects/ad353xr_iio/ad3530r_hardware_interface.png
  doc/sphinx/source/projects/ad353xr_iio/ad353xr_iio.rst
  doc/sphinx/source/projects/ad353xr_iio/sampling_frequency_calculation.png
  doc/sphinx/source/projects/index.rst
Labels: documentation

#123 doc: Update Sphinx documentation
  doc/sphinx/source/build/project_build_stm32.rst
  doc/sphinx/source/build/stm32_build_project.png
  doc/sphinx/source/build/stm32_convert_to_binary.png
Labels: documentation

#122 projects: ad7091r: Add minor updates
  projects/ad7091r_iio/STM32/.extSettings
  projects/ad7091r_iio/STM32/ad7091r_iio.ioc
  projects/ad7091r_iio/app/app_config.c
  projects/ad7091r_iio/app/app_config.h
  projects/ad7091r_iio/app/app_config_stm32.c
  projects/ad7091r_iio/scripts/ad7091r_data_capture.py
Labels: minor_updates
